# Generated by Django 4.1.2 on 2022-10-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='unitprice',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
        ),
    ]
