# Generated by Django 4.1.2 on 2022-12-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_ingredients_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='purchases',
            name='menu_item',
            field=models.ManyToManyField(to='inventory.menuitem'),
        ),
    ]
