# Generated by Django 4.1.2 on 2022-12-31 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_purchases_menu_item_purchases_menu_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='purchases',
            name='menu_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitem'),
        ),
    ]
